FROM node:20
WORKDIR /app

COPY package*.json ./

# Clean install with proper native binaries
RUN npm cache clean --force && \
    npm install --legacy-peer-deps && \
    npm install @rollup/rollup-linux-x64-gnu --save-optional

COPY . .

ARG VITE_PORT VITE_APP_ENV
ENV VITE_PORT=${VITE_PORT} VITE_APP_ENV=${VITE_APP_ENV}

# Build en prod seulement
RUN if [ "$VITE_APP_ENV" = "prod" ]; then npm run build; fi

CMD [ "/bin/sh", "-c", "if [ \"$VITE_APP_ENV\" = \"prod\" ]; then npm install -g serve && serve -s dist -l ${VITE_PORT}; else npm run dev; fi" ]